openapi: 3.0.3
info:
  title: Help

paths:
  /produtos:
    get:
      summary: Lista todos os produtos
      responses:
        '200':
          description: Lista de produtos retornada com sucesso
        '404':
          description: Nenhum produto encontrado

    post:
      summary: Cria um novo produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                preco:
                  type: number
                  format: float
                descricao:
                  type: string
              required:
                - nome
                - preco
      responses:
        '201':
          description: Produto criado com sucesso
        '406':
          description: Caso falte informação
        '500':
          description: Caso ocorra erro no servidor

  /produtos/{id}:
    get:
      summary: Retorna um produto específico
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produto
          schema:
            type: string
      responses:
        '200':
          description: Produto retornado com sucesso
        '404':
          description: Produto não encontrado

    post:
      summary: Atualiza um produto existente
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                preco:
                  type: number
                  format: float
                descricao:
                  type: string
              required:
                - nome
                - preco
      responses:
        '200':
          description: Produto atualizado com sucesso
        '404':
          description: Produto não encontrado
        '406':
          description: Caso falte informação
        '500':
          description: Caso ocorra erro no servidor

    delete:
      summary: Deleta um produto existente
      parameters:
        - name: id
          in: path
          required: true
          description: ID do produto
          schema:
            type: string
      responses:
        '204':
          description: Produto deletado com sucesso
        '404':
          description: Produto não encontrado

  /clientes:
    get:
      summary: Lista todos os clientes
      responses:
        '200':
          description: Lista de clientes retornada com sucesso
        '404':
          description: Nenhum cliente encontrado

    post:
      summary: Cria um novo cliente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                senha:
                  type: string
                nome:
                  type: string
              required:
                - email
                - senha
      responses:
        '201':
          description: Cliente criado com sucesso
        '406':
          description: Caso faltem informações (email e senha)
        '500':
          description: Caso ocorra erro no servidor

  /clientes/{id}:
    get:
      summary: Retorna um cliente específico
      parameters:
        - name: id
          in: path
          required: true
          description: ID do cliente
          schema:
            type: string
      responses:
        '200':
          description: Cliente retornado com sucesso
        '404':
          description: Cliente não encontrado

    post:
      summary: Atualiza um cliente existente
      parameters:
        - name: id
          in: path
          required: true
          description: ID do cliente
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                senha:
                  type: string
                nome:
                  type: string
              required:
                - email
                - senha
      responses:
        '200':
          description: Cliente atualizado com sucesso
        '404':
          description: Cliente não encontrado
        '406':
          description: Caso faltem informações
        '500':
          description: Caso ocorra erro no servidor

    delete:
      summary: Deleta um cliente existente
      parameters:
        - name: id
          in: path
          required: true
          description: ID do cliente
          schema:
            type: string
      responses:
        '204':
          description: Cliente deletado com sucesso
        '404':
          description: Cliente não encontrado

  /auth:
    post:
      summary: Faz o login do cliente e retorna um token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                senha:
                  type: string
              required:
                - email
                - senha
      responses:
        '200':
          description: Login bem-sucedido, token JWT retornado
        '401':
          description: Credenciais inválidas

    delete:
      summary: Faz o logout do cliente
      responses:
        '200':
          description: Logout realizado com sucesso
